// <auto-generated />
using System;
using MedicalSimulation.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalSimulation.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127092947_AddCarotidArteryStentingAndFixes")]
    partial class AddCarotidArteryStentingAndFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalSimulation.Core.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserProgressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SimulationId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserProgressId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("ValidEmployeeIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("ValidEmployeeIdId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.InstructorSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstructorSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Skin and related conditions",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Brain and nervous system surgery",
                            Name = "Neurosurgery"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Heart and cardiovascular system",
                            Name = "Cardiology"
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalStates")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Simulations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 586, DateTimeKind.Utc).AddTicks(392),
                            Description = "Master the subcuticular running suture technique with this interactive video simulation.",
                            Difficulty = 2,
                            EstimatedMinutes = 15,
                            IsActive = true,
                            SpecialtyId = 1,
                            ThumbnailUrl = "/pictures/suture.png",
                            Title = "Subcuticular Running Suture",
                            TotalStates = 6
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 586, DateTimeKind.Utc).AddTicks(2863),
                            Description = "Learn the critical steps and anatomical considerations in performing a posterior neck craniectomy.",
                            Difficulty = 3,
                            EstimatedMinutes = 10,
                            IsActive = true,
                            SpecialtyId = 2,
                            ThumbnailUrl = "/pictures/craniectomy.png",
                            Title = "Posterior Neck Craniectomy",
                            TotalStates = 6
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 586, DateTimeKind.Utc).AddTicks(2868),
                            Description = "Learn the essential steps and techniques for performing carotid artery stenting to restore blood flow.",
                            Difficulty = 3,
                            EstimatedMinutes = 10,
                            IsActive = true,
                            SpecialtyId = 3,
                            ThumbnailUrl = "/pictures/carotid-stenting.png",
                            Title = "Carotid Artery Stenting",
                            TotalStates = 6
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#10b981",
                            Description = "Skin and related conditions, including surgical procedures",
                            DisplayOrder = 1,
                            IconClass = "fa-hand-holding-medical",
                            IsActive = true,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#8b5cf6",
                            Description = "Brain, spinal cord, and nervous system procedures",
                            DisplayOrder = 2,
                            IconClass = "fa-brain",
                            IsActive = true,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ef4444",
                            Description = "Heart and cardiovascular system procedures",
                            DisplayOrder = 3,
                            IconClass = "fa-heart-pulse",
                            IsActive = true,
                            Name = "Cardiology"
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.SurgeryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerOptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotspotDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateNumber")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("SurgeryStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Click the correct entry point for the first intradermal bite.",
                            HotspotDataJson = "{\"pauseTime\":0.922,\"x\":55.21,\"y\":52.76,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click the correct entry point for the first intradermal bite.",
                            SimulationId = 1,
                            StateName = "First Intradermal Bite Entry",
                            StateNumber = 1,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Click where the needle should exit on the opposite side.",
                            HotspotDataJson = "{\"pauseTime\":6.423,\"x\":50,\"y\":72.76,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click where the needle should exit on the opposite side.",
                            SimulationId = 1,
                            StateName = "Needle Exit Point",
                            StateNumber = 2,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Click where the suture loop should rest before tightening.",
                            HotspotDataJson = "{\"pauseTime\":12.13,\"x\":48.81,\"y\":63.01,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click where the suture loop should rest before tightening.",
                            SimulationId = 1,
                            StateName = "Suture Loop Position",
                            StateNumber = 3,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Where should the cut be made?",
                            HotspotDataJson = "{\"pauseTime\":51.449,\"x\":57.68,\"y\":27.57,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Where should the cut be made?",
                            SimulationId = 1,
                            StateName = "Cut Placement",
                            StateNumber = 4,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 5,
                            AnswerOptionsJson = "[\"Begin the next intradermal bite at equal spacing\",\"Cut the suture ends\",\"Tighten further to blanch the skin\",\"Place a superficial interrupted stitch\"]",
                            CorrectAnswerIndex = 0,
                            Description = "What is the next correct step after securing this knot in a running subcuticular suture?",
                            HotspotDataJson = "{\"pauseTime\":57.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the next correct step after securing this knot in a running subcuticular suture?",
                            SimulationId = 1,
                            StateName = "Next Step After Knot",
                            StateNumber = 5,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Click the correct point to place the next intradermal bite.",
                            HotspotDataJson = "{\"pauseTime\":60,\"x\":42.32,\"y\":58.94,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click the correct point to place the next intradermal bite.",
                            SimulationId = 1,
                            StateName = "Next Intradermal Bite",
                            StateNumber = 6,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Click on the correct incision line for a posterior neck craniectomy.",
                            HotspotDataJson = "{\"pauseTime\":3.765,\"x\":50.46,\"y\":38.95,\"radius\":5}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click on the correct incision line for a posterior neck craniectomy.",
                            SimulationId = 2,
                            StateName = "Incision Line Identification",
                            StateNumber = 1,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 8,
                            AnswerOptionsJson = "[\"Skin and subcutaneous tissue\",\"Trapezius muscle\",\"Deep cervical fascia and underlying vital structures\",\"Vertebral spinous processes\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Identify the critical structure before proceeding.",
                            HotspotDataJson = "{\"pauseTime\":16.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Which structure must be clearly identified before proceeding further in a posterior neck carcinectomy?",
                            SimulationId = 2,
                            StateName = "Structure Identification",
                            StateNumber = 2,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 9,
                            AnswerOptionsJson = "[\"Excise only the visibly abnormal tissue\",\"Cut as close as possible to minimize tissue loss\",\"Include an adequate margin of healthy tissue around the lesion\",\"Delay margin planning until closure\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Understanding the correct principle for defining resection margins.",
                            HotspotDataJson = "{\"pauseTime\":28.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the correct principle for defining the resection margin during a carcinectomy?",
                            SimulationId = 2,
                            StateName = "Resection Margin Principles",
                            StateNumber = 3,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Point where the next incision is to be done.",
                            HotspotDataJson = "{\"pauseTime\":56.669,\"x\":49.91,\"y\":40.25,\"radius\":5}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Point where the next incision is to be done.",
                            SimulationId = 2,
                            StateName = "Next Incision Point",
                            StateNumber = 4,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 11,
                            AnswerOptionsJson = "[\"Skin flap\",\"Paraspinal muscles\",\"Spinal cord and dura mater\",\"Trachea\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Identify the structure that must be actively protected during dissection.",
                            HotspotDataJson = "{\"pauseTime\":81.431}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Which structure must be actively protected while performing this dissection?",
                            SimulationId = 2,
                            StateName = "Structure Protection",
                            StateNumber = 5,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 12,
                            AnswerOptionsJson = "[\"Immediate skin closure with sutures\",\"Irrigation and leave the wound open\",\"Apply a sterile pressure dressing / protective dressing\",\"Begin deep muscle reconstruction\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Determine the appropriate next step after excising the lesion.",
                            HotspotDataJson = "{\"pauseTime\":93.431}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the next appropriate step after excising the lesion?",
                            SimulationId = 2,
                            StateName = "Post-Excision Management",
                            StateNumber = 6,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 13,
                            AnswerOptionsJson = "[\"Radial artery\",\"Radial vein\",\"Ulnar artery\",\"Cephalic vein\"]",
                            CorrectAnswerIndex = 0,
                            Description = "Identify the vessel being accessed for arterial entry.",
                            HotspotDataJson = "{\"pauseTime\":10}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Which vessel is being accessed for arterial entry?",
                            SimulationId = 3,
                            StateName = "Arterial Access Vessel",
                            StateNumber = 1,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        },
                        new
                        {
                            Id = 14,
                            AnswerOptionsJson = "[\"Deploy the carotid stent\",\"Insert an introducer sheath over the guidewire\",\"Inflate the balloon to dilate the artery\",\"Close the puncture site\"]",
                            CorrectAnswerIndex = 1,
                            Description = "Determine the next step after successful arterial puncture and guidewire placement.",
                            HotspotDataJson = "{\"pauseTime\":15}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "After successful arterial puncture and guidewire placement, what is the next step in carotid artery stenting?",
                            SimulationId = 3,
                            StateName = "Next Step After Guidewire",
                            StateNumber = 2,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        },
                        new
                        {
                            Id = 15,
                            AnswerOptionsJson = "[\"To inject contrast directly into the brain\",\"To maintain stable arterial access for catheter and device passage\",\"To remove arterial plaque\",\"To close the puncture site\"]",
                            CorrectAnswerIndex = 1,
                            Description = "Understand the primary purpose of inserting the sheath.",
                            HotspotDataJson = "{\"pauseTime\":28}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the primary purpose of inserting this sheath at this stage of the procedure?",
                            SimulationId = 3,
                            StateName = "Purpose of Sheath Insertion",
                            StateNumber = 3,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        },
                        new
                        {
                            Id = 16,
                            AnswerOptionsJson = "[\"To dissolve the plaque\",\"To visualize the carotid artery and identify the stenosis\",\"To widen the artery\",\"To anesthetize the vessel\"]",
                            CorrectAnswerIndex = 1,
                            Description = "Identify why contrast dye is injected at this stage.",
                            HotspotDataJson = "{\"pauseTime\":45}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Why is contrast dye injected at this stage of the carotid artery stenting procedure?",
                            SimulationId = 3,
                            StateName = "Contrast Dye Purpose",
                            StateNumber = 4,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        },
                        new
                        {
                            Id = 17,
                            AnswerOptionsJson = "[\"In the subclavian artery\",\"In the internal carotid artery at the site of stenosis\",\"In the external carotid artery\",\"In the aortic arch\"]",
                            CorrectAnswerIndex = 1,
                            Description = "Identify the correct location for stent deployment.",
                            HotspotDataJson = "{\"pauseTime\":55}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Where should the stent be deployed during a carotid artery stenting procedure?",
                            SimulationId = 3,
                            StateName = "Stent Deployment Location",
                            StateNumber = 5,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        },
                        new
                        {
                            Id = 18,
                            AnswerOptionsJson = "[\"To dissolve the plaque chemically\",\"To widen the narrowed artery and restore blood flow\",\"To block blood flow to the brain\",\"To remove the artery wall\"]",
                            CorrectAnswerIndex = 1,
                            Description = "Understand the primary purpose of deploying the stent.",
                            HotspotDataJson = "{\"pauseTime\":100,\"endTime\":106}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the primary purpose of deploying the stent at this location?",
                            SimulationId = 3,
                            StateName = "Purpose of Stent Deployment",
                            StateNumber = 6,
                            VideoUrl = "/videos/simulations/Cartoid-artery-stenting.mp4"
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ValidInstructorEmployeeId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ValidInstructorEmployeeIds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 585, DateTimeKind.Utc).AddTicks(6668),
                            EmployeeId = "EMP001",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 585, DateTimeKind.Utc).AddTicks(8446),
                            EmployeeId = "EMP002",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 585, DateTimeKind.Utc).AddTicks(8451),
                            EmployeeId = "EMP003",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 585, DateTimeKind.Utc).AddTicks(8452),
                            EmployeeId = "EMP004",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 29, 46, 585, DateTimeKind.Utc).AddTicks(8454),
                            EmployeeId = "EMP005",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Feedback", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.Simulation", "Simulation")
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.UserProgress", "UserProgress")
                        .WithMany()
                        .HasForeignKey("UserProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Simulation");

                    b.Navigation("Student");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Instructor", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.InstructorSpecialization", "Specialization")
                        .WithMany("Instructors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.ValidInstructorEmployeeId", "ValidEmployeeId")
                        .WithMany("Instructors")
                        .HasForeignKey("ValidEmployeeIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Specialization");

                    b.Navigation("ValidEmployeeId");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Specialty", "Specialty")
                        .WithMany("Simulations")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Student", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.SurgeryState", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Simulation", "Simulation")
                        .WithMany("States")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.UserProgress", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Simulation", "Simulation")
                        .WithMany("UserProgress")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "User")
                        .WithMany("UserProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.InstructorSpecialization", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.Navigation("States");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Specialty", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ValidInstructorEmployeeId", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
