// <auto-generated />
using System;
using MedicalSimulation.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalSimulation.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119100810_AddStudentAndInstructorTables")]
    partial class AddStudentAndInstructorTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalSimulation.Core.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalStates")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Simulations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 10, 8, 9, 402, DateTimeKind.Utc).AddTicks(5480),
                            Description = "Master the subcuticular running suture technique with this interactive video simulation.",
                            Difficulty = 2,
                            EstimatedMinutes = 15,
                            IsActive = true,
                            SpecialtyId = 1,
                            ThumbnailUrl = "/pictures/suture.png",
                            Title = "Subcuticular Running Suture",
                            TotalStates = 6
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 10, 8, 9, 402, DateTimeKind.Utc).AddTicks(8053),
                            Description = "Learn the critical steps and anatomical considerations in performing a posterior neck craniectomy.",
                            Difficulty = 3,
                            EstimatedMinutes = 10,
                            IsActive = true,
                            SpecialtyId = 1,
                            ThumbnailUrl = "/pictures/craniectomy.png",
                            Title = "Posterior Neck Craniectomy",
                            TotalStates = 6
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fundamental techniques for all surgeons",
                            DisplayOrder = 0,
                            IsActive = true,
                            Name = "Basic Surgical Skills"
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.SurgeryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerOptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotspotDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateNumber")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("SurgeryStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Click the correct entry point for the first intradermal bite.",
                            HotspotDataJson = "{\"pauseTime\":0.922,\"x\":55.21,\"y\":52.76,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click the correct entry point for the first intradermal bite.",
                            SimulationId = 1,
                            StateName = "First Intradermal Bite Entry",
                            StateNumber = 1,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Click where the needle should exit on the opposite side.",
                            HotspotDataJson = "{\"pauseTime\":6.423,\"x\":50,\"y\":72.76,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click where the needle should exit on the opposite side.",
                            SimulationId = 1,
                            StateName = "Needle Exit Point",
                            StateNumber = 2,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Click where the suture loop should rest before tightening.",
                            HotspotDataJson = "{\"pauseTime\":12.13,\"x\":48.81,\"y\":63.01,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click where the suture loop should rest before tightening.",
                            SimulationId = 1,
                            StateName = "Suture Loop Position",
                            StateNumber = 3,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Where should the cut be made?",
                            HotspotDataJson = "{\"pauseTime\":51.449,\"x\":57.68,\"y\":27.57,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Where should the cut be made?",
                            SimulationId = 1,
                            StateName = "Cut Placement",
                            StateNumber = 4,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 5,
                            AnswerOptionsJson = "[\"Begin the next intradermal bite at equal spacing\",\"Cut the suture ends\",\"Tighten further to blanch the skin\",\"Place a superficial interrupted stitch\"]",
                            CorrectAnswerIndex = 0,
                            Description = "What is the next correct step after securing this knot in a running subcuticular suture?",
                            HotspotDataJson = "{\"pauseTime\":57.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the next correct step after securing this knot in a running subcuticular suture?",
                            SimulationId = 1,
                            StateName = "Next Step After Knot",
                            StateNumber = 5,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Click the correct point to place the next intradermal bite.",
                            HotspotDataJson = "{\"pauseTime\":60,\"x\":42.32,\"y\":58.94,\"radius\":10}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click the correct point to place the next intradermal bite.",
                            SimulationId = 1,
                            StateName = "Next Intradermal Bite",
                            StateNumber = 6,
                            VideoUrl = "/videos/simulations/subcuticular-running-suture.mp4"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Click on the correct incision line for a posterior neck craniectomy.",
                            HotspotDataJson = "{\"pauseTime\":3.765,\"x\":50.46,\"y\":38.95,\"radius\":5}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Click on the correct incision line for a posterior neck craniectomy.",
                            SimulationId = 2,
                            StateName = "Incision Line Identification",
                            StateNumber = 1,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 8,
                            AnswerOptionsJson = "[\"Skin and subcutaneous tissue\",\"Trapezius muscle\",\"Deep cervical fascia and underlying vital structures\",\"Vertebral spinous processes\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Identify the critical structure before proceeding.",
                            HotspotDataJson = "{\"pauseTime\":16.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Which structure must be clearly identified before proceeding further in a posterior neck carcinectomy?",
                            SimulationId = 2,
                            StateName = "Structure Identification",
                            StateNumber = 2,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 9,
                            AnswerOptionsJson = "[\"Excise only the visibly abnormal tissue\",\"Cut as close as possible to minimize tissue loss\",\"Include an adequate margin of healthy tissue around the lesion\",\"Delay margin planning until closure\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Understanding the correct principle for defining resection margins.",
                            HotspotDataJson = "{\"pauseTime\":28.000}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the correct principle for defining the resection margin during a carcinectomy?",
                            SimulationId = 2,
                            StateName = "Resection Margin Principles",
                            StateNumber = 3,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Point where the next incision is to be done.",
                            HotspotDataJson = "{\"pauseTime\":56.669,\"x\":49.91,\"y\":40.25,\"radius\":5}",
                            InteractionType = "click-hotspot",
                            LayersJson = "[]",
                            QuestionText = "Point where the next incision is to be done.",
                            SimulationId = 2,
                            StateName = "Next Incision Point",
                            StateNumber = 4,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 11,
                            AnswerOptionsJson = "[\"Skin flap\",\"Paraspinal muscles\",\"Spinal cord and dura mater\",\"Trachea\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Identify the structure that must be actively protected during dissection.",
                            HotspotDataJson = "{\"pauseTime\":81.431}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "Which structure must be actively protected while performing this dissection?",
                            SimulationId = 2,
                            StateName = "Structure Protection",
                            StateNumber = 5,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        },
                        new
                        {
                            Id = 12,
                            AnswerOptionsJson = "[\"Immediate skin closure with sutures\",\"Irrigation and leave the wound open\",\"Apply a sterile pressure dressing / protective dressing\",\"Begin deep muscle reconstruction\"]",
                            CorrectAnswerIndex = 2,
                            Description = "Determine the appropriate next step after excising the lesion.",
                            HotspotDataJson = "{\"pauseTime\":93.431}",
                            InteractionType = "mcq",
                            LayersJson = "[]",
                            QuestionText = "What is the next appropriate step after excising the lesion?",
                            SimulationId = 2,
                            StateName = "Post-Excision Management",
                            StateNumber = 6,
                            VideoUrl = "/videos/simulations/craniectomy.mp4"
                        });
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClinicalErrorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailedStepDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceMetricsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VitalSignsHistoryJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Instructor", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Specialty", "Specialty")
                        .WithMany("Simulations")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Student", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.SurgeryState", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Simulation", "Simulation")
                        .WithMany("States")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.UserProgress", b =>
                {
                    b.HasOne("MedicalSimulation.Core.Models.Simulation", "Simulation")
                        .WithMany("UserProgress")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSimulation.Core.Models.ApplicationUser", "User")
                        .WithMany("UserProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Simulation", b =>
                {
                    b.Navigation("States");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.Specialty", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("MedicalSimulation.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
